ARG NODE_VERSION=20
ARG SERVER_PORT=3001

FROM node:$NODE_VERSION-bookworm AS base

WORKDIR /app

FROM base AS builder

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

COPY . .

RUN yarn lerna bootstrap
RUN yarn workspace server build
RUN yarn cache clean && rm -rf /usr/local/share/.cache/yarn

FROM node:$NODE_VERSION-bookworm-slim AS production
WORKDIR /app

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

COPY --from=builder /app/packages/server/dist/ /app/dist
COPY --from=builder /app/packages/server/package.json /app/package.json
COPY --from=builder /app/yarn.lock /app/yarn.lock

RUN yarn install --production=true \
  && yarn cache clean \
  && rm -rf /usr/local/share/.cache/yarn

EXPOSE $SERVER_PORT
CMD [ "node", "/app/dist/index.js" ]
